# Generated by Django 5.1.5 on 2025-01-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceproviders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
