# Generated by Django 5.1.5 on 2025-01-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceproviders", "0002_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
