# Generated by Django 5.1.3 on 2024-12-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('government_id', models.FileField(blank=True, null=True, upload_to='uploads/ids/')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_category', models.CharField(max_length=50)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='uploads/licenses/')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description', models.TextField()),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('insurance_proof', models.FileField(blank=True, null=True, upload_to='uploads/insurance/')),
                ('references', models.TextField(blank=True, null=True)),
                ('reviews_link', models.URLField(blank=True, null=True)),
                ('tools_and_software', models.TextField(blank=True, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('consent_for_background_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
