# Generated by Django 5.1.5 on 2025-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
